modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = "https://github.com/ProfessorFichte/Elemental-Wizards/issues"
license = "ARR"

[[mods]]
modId = "elemental_wizards_rpg"
version = "${version}"
displayName = "Elemental Wizards"
authors = "Fichte"
description = '''
Master the elements to overcome your foes! Spell Engine Add-On
'''
logoFile = "icon.png"

[[dependencies.elemental_wizards_rpg]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.elemental_wizards_rpg]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.elemental_wizards_rpg]]
modId = "spell_engine"
type = "required"
versionRange = "[${spell_engine_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.elemental_wizards_rpg]]
modId = "wizards"
type = "required"
versionRange = "[${wizards_version},)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "elemental_wizards_rpg.mixins.json"
